service: my-lambda-service

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  # Do not include AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY here
  environment:
    # You can include other environment variables that your function needs
    OTHER_ENV_VAR: some-value

functions:
  register:
    handler: app.register
    events:
      - http:
          path: register
          method: post

  calculate_score:
    handler: app.calculate_score
    events:
      - http:
          path: calculate_score
          method: post
