service: lungHealthCalculator

provider:
  name: aws
  runtime: python3.9
  region: us-west-2

functions:
  calculateLungHealth:
    handler: handler.main
    events:
      - http:
          path: calculate-lung-health
          method: post
          cors: true
